# -*- coding: utf-8 -*-
"""Metode Biseksi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aXVWVJ9nLEPsPrlSAgLFYkeb5lCUDKBK
"""

import numpy as np
import matplotlib.pyplot as plt
import math

y = input('Masukkan persamaan fungsi x : ')

a = float((input('Masukkan nilai a : ')))
b = float((input('Masukan nilai b : ')))

print('Akar persaaman adalah ', a, ' dan ', b)

def f(x):
  z = y.replace('x',str(x))
  return eval(z)

def biseksi(a,b,tot):
  n = 1
  if f(a) * f(b) > 0:
    print('Tidak memiliki akar persamaan')
  else:
    while abs(b-a) > tot:
      x = (a+b)/2
      print(n,'\t', round(a,4),'      \t', round (b,4),'      \t',round(x,4),'        \t', round(f(a),4),'        \t',round(f(b),4), round(f(x),4))

      if f(x) == 0:
        print('Akar persamaannya adalah ', x)
        break
      elif f(a) * f(x) < 0:
        b = x
      else:
        a = x
      n += 1

    print('Akar persamaanya adalah =  ', round(a,11), ' dan ', round(b,11))

print('n\t a    \t\t b    \t\t  xn    \t\t    f(a)    \t\t    f(b)    \t\t    f(xn)')
print('                                                                            ')
biseksi(a, b, 0.001)

x = np.linspace(a, b)
plt.plot(x, eval(y))
plt.grid()
plt.show()