# -*- coding: utf-8 -*-
"""Riemann.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UWKyxyFZQDkWHb6e9CwNZ-tUq0iVxD8u
"""

import numpy as np
import matplotlib.pyplot as plt

f = lambda x: np.exp(x)

a = float(input('Masukkan nilai batas bawah: '))
b = float(input('Masukkan nilai batas atas: '))
n = int(input('Masukkan nilai N:'))

# 1

dx=(b-a)/n

left = np.linspace(a,b,n)
mid = np.linspace(dx/2,b-dx/2,n)
right = np.linspace(dx,b,n)

left_sum=np.sum(f(left)*dx)
mid_sum = np.sum(f(mid)*dx)
right_sum = np.sum(f(right)*dx)

print('Reinmann kiri : ',left_sum)
print("Riemann Tengah : ",mid_sum)
print('Riemann Kanan : ',right_sum)