# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Fk9aSwDkZk4KYn_tFw--jD0oM3-eT-V
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy
import matplotlib.pyplot as plt
# %matplotlib inline

f = lambda x: 4*x*x*x-15*x*x+17*x-6
x, xb = -1, 3

itemax=100
eps = 0.005
n=1
newX = x - ((f(x) * (x - xb) ) / (f(x) - f(xb)))
print("|it|       x   |   xx    |     fx   |   | fx|   |      fxx    |")
print("---------------------------------------------------------------")
print('|{:2}|{:=9.5f}|{:=9.5f}|{:=9.5f}|{:=9.5f}|{:=9.5f}|'.format(n,x,xb,f(x),abs(f(x)),f(xb)))
for n in range(2, itemax):
  if abs(f(x)) >= eps:
    newX = x - ((f(x) * (x - xb) ) / (f(x) - f(xb)))
    xb = x
    x = newX
    print('|{:2}|{:=9.5f}|{:=9.5f}|{:=9.5f}|{:=9.5f}|{:=9.5f}|'.format(n,x,xb,f(x),abs(f(x)),f(xb)))
print('Akar ditemukan pada x = {:8.6f}' .format(newX))


x = numpy.linspace(0.0 ,1 , 100)

fig = plt.figure()
ax = fig.add_subplot(111)
print('')
ax.plot(x, f(x), 'b')
ax.text(newX-0.01,0.1, '{:=8.6f}' .format(xi))
ax.plot(x,numpy.zeros(x.shape),'r--')